name: jetmarket
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  dio: ^5.3.4
  flutter_screenutil: ^5.9.0
  dotted_border: ^2.1.0
  permission_handler: ^11.0.1
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  intl: ^0.19.0
  device_preview: ^1.1.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  carousel_slider: ^4.2.1
  flutter_staggered_grid_view: ^0.7.0
  firebase_core: ^2.25.4
  firebase_messaging: ^14.7.15
  flutter_local_notifications: ^16.3.2
  google_maps_flutter: ^2.5.0
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  shared_preferences: ^2.2.2
  syncfusion_flutter_barcodes: ^24.2.4
  awesome_dialog: ^3.1.0
  url_launcher: ^6.2.1
  calendar_date_picker2: ^0.5.3
  infinite_scroll_pagination: ^4.0.0
  easy_image_viewer: ^1.3.2
  flutter_widget_from_html: ^0.14.10+1
  pull_to_refresh: ^2.0.0
  cloud_firestore: ^4.15.4
  scrollable_positioned_list: ^0.3.8
  scroll_to_index: ^3.0.1
  rxdart: ^0.27.7
  uni_links: ^0.5.1
  share_plus: ^7.2.2
  firebase_dynamic_links: ^5.4.13
  firebase_analytics: ^10.8.5
  dropdown_button2: ^2.3.9
  flutter_native_splash: ^2.3.10


flutter_native_splash:
  background_image: assets/images/splash.png
  android: true
  ios: true


dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/svg/
    - assets/images/
    - assets/env/
    - assets/json/
  uses-material-design: true

